### ISSUE TITLE
Error trying to run project

### ISSUE THREAD

**Issue by fredkorts** [GeekyAnts/vue-js-animation-starter-kit#1]
Hey, I wanted to run your project, but I got a fatal error on start up.

https://gyazo.com/66d73f9e71373671c36fd7c21cb6b33a

Trying to install those dependencies results in this error

https://gyazo.com/7ab75d04775d274fa84e4bacb172cd1d

**Comment by vanishree1** [comment]
This error is because of vue-awesome package version. It's fixed now.
