### ISSUE TITLE
Question ?

### ISSUE THREAD

**Issue by mbj36** [GeekyAnts/vue-js-animation-starter-kit#2]
Thanks for the starter kit, really liked the smooth transition

Is there any reason for registering  component globally in `main.js` file ?

<img width="355" alt="screen shot 2018-04-15 at 1 03 39 am" src="https://user-images.githubusercontent.com/9936881/38771898-e0bca310-4048-11e8-9393-b8b868b6d2ea.png">

**Comment by vanishree1** [comment]
Since we have used Icon component in the entire application we need to register globally.No need to register other components globally.

**Comment by mbj36** [comment]
Wouldn't it be sufficient if we just use `Vue.use(Icon)` instead of using `Vue.component('Icon', Icon)` and passing in a component ?

Keeping in mind, we are using vue-cli
